image: alpine

pages:
  script:
  - apk --no-cache add py-pip python3
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - apk --no-cache add make
  - cd documentation
  - make html
  - cd ..
  - mv documentation/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
