// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dbm

import (
	parameters "ParsinServer/dbm/parameters"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	sync "sync"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3b8810b5DecodeParsinServerDbm(in *jlexer.Lexer, out *ResultDataStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "AlgoAccuracy":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.AlgoAccuracy = make(map[string]int)
				} else {
					out.AlgoAccuracy = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 int
					v1 = int(in.Int())
					(out.AlgoAccuracy)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "AlgoAccuracyLoc":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.AlgoAccuracyLoc = make(map[string]map[string]int)
				} else {
					out.AlgoAccuracyLoc = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 map[string]int
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						if !in.IsDelim('}') {
							v2 = make(map[string]int)
						} else {
							v2 = nil
						}
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v3 int
							v3 = int(in.Int())
							(v2)[key] = v3
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.AlgoAccuracyLoc)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "UserHistory":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.UserHistory = make(map[string][]parameters.UserPositionJSON)
				} else {
					out.UserHistory = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v4 []parameters.UserPositionJSON
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						in.Delim('[')
						if v4 == nil {
							if !in.IsDelim(']') {
								v4 = make([]parameters.UserPositionJSON, 0, 1)
							} else {
								v4 = []parameters.UserPositionJSON{}
							}
						} else {
							v4 = (v4)[:0]
						}
						for !in.IsDelim(']') {
							var v5 parameters.UserPositionJSON
							(v5).UnmarshalEasyJSON(in)
							v4 = append(v4, v5)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.UserHistory)[key] = v4
					in.WantComma()
				}
				in.Delim('}')
			}
		case "UserResults":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.UserResults = make(map[string][]parameters.UserPositionJSON)
				} else {
					out.UserResults = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v6 []parameters.UserPositionJSON
					if in.IsNull() {
						in.Skip()
						v6 = nil
					} else {
						in.Delim('[')
						if v6 == nil {
							if !in.IsDelim(']') {
								v6 = make([]parameters.UserPositionJSON, 0, 1)
							} else {
								v6 = []parameters.UserPositionJSON{}
							}
						} else {
							v6 = (v6)[:0]
						}
						for !in.IsDelim(']') {
							var v7 parameters.UserPositionJSON
							(v7).UnmarshalEasyJSON(in)
							v6 = append(v6, v7)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.UserResults)[key] = v6
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b8810b5EncodeParsinServerDbm(out *jwriter.Writer, in ResultDataStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"AlgoAccuracy\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.AlgoAccuracy == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.AlgoAccuracy {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				out.Int(int(v8Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"AlgoAccuracyLoc\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.AlgoAccuracyLoc == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v9First := true
			for v9Name, v9Value := range in.AlgoAccuracyLoc {
				if v9First {
					v9First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v9Name))
				out.RawByte(':')
				if v9Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v10First := true
					for v10Name, v10Value := range v9Value {
						if v10First {
							v10First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v10Name))
						out.RawByte(':')
						out.Int(int(v10Value))
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"UserHistory\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.UserHistory == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v11First := true
			for v11Name, v11Value := range in.UserHistory {
				if v11First {
					v11First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v11Name))
				out.RawByte(':')
				if v11Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v12, v13 := range v11Value {
						if v12 > 0 {
							out.RawByte(',')
						}
						(v13).MarshalEasyJSON(out)
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"UserResults\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.UserResults == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v14First := true
			for v14Name, v14Value := range in.UserResults {
				if v14First {
					v14First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v14Name))
				out.RawByte(':')
				if v14Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v15, v16 := range v14Value {
						if v15 > 0 {
							out.RawByte(',')
						}
						(v16).MarshalEasyJSON(out)
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResultDataStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b8810b5EncodeParsinServerDbm(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResultDataStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b8810b5EncodeParsinServerDbm(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResultDataStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b8810b5DecodeParsinServerDbm(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResultDataStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b8810b5DecodeParsinServerDbm(l, v)
}
func easyjson3b8810b5DecodeParsinServerDbm1(in *jlexer.Lexer, out *RawDataStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Fingerprints":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Fingerprints = make(map[string]parameters.Fingerprint)
				} else {
					out.Fingerprints = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v17 parameters.Fingerprint
					(v17).UnmarshalEasyJSON(in)
					(out.Fingerprints)[key] = v17
					in.WantComma()
				}
				in.Delim('}')
			}
		case "FingerprintsOrdering":
			if in.IsNull() {
				in.Skip()
				out.FingerprintsOrdering = nil
			} else {
				in.Delim('[')
				if out.FingerprintsOrdering == nil {
					if !in.IsDelim(']') {
						out.FingerprintsOrdering = make([]string, 0, 4)
					} else {
						out.FingerprintsOrdering = []string{}
					}
				} else {
					out.FingerprintsOrdering = (out.FingerprintsOrdering)[:0]
				}
				for !in.IsDelim(']') {
					var v18 string
					v18 = string(in.String())
					out.FingerprintsOrdering = append(out.FingerprintsOrdering, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b8810b5EncodeParsinServerDbm1(out *jwriter.Writer, in RawDataStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Fingerprints\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Fingerprints == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v19First := true
			for v19Name, v19Value := range in.Fingerprints {
				if v19First {
					v19First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v19Name))
				out.RawByte(':')
				(v19Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"FingerprintsOrdering\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.FingerprintsOrdering == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.FingerprintsOrdering {
				if v20 > 0 {
					out.RawByte(',')
				}
				out.String(string(v21))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawDataStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b8810b5EncodeParsinServerDbm1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawDataStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b8810b5EncodeParsinServerDbm1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawDataStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b8810b5DecodeParsinServerDbm1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawDataStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b8810b5DecodeParsinServerDbm1(l, v)
}
func easyjson3b8810b5DecodeParsinServerDbm2(in *jlexer.Lexer, out *MiddleDataStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "NetworkMacs":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.NetworkMacs = make(map[string]map[string]bool)
				} else {
					out.NetworkMacs = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v22 map[string]bool
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						if !in.IsDelim('}') {
							v22 = make(map[string]bool)
						} else {
							v22 = nil
						}
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v23 bool
							v23 = bool(in.Bool())
							(v22)[key] = v23
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.NetworkMacs)[key] = v22
					in.WantComma()
				}
				in.Delim('}')
			}
		case "NetworkLocs":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.NetworkLocs = make(map[string]map[string]bool)
				} else {
					out.NetworkLocs = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v24 map[string]bool
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						if !in.IsDelim('}') {
							v24 = make(map[string]bool)
						} else {
							v24 = nil
						}
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v25 bool
							v25 = bool(in.Bool())
							(v24)[key] = v25
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.NetworkLocs)[key] = v24
					in.WantComma()
				}
				in.Delim('}')
			}
		case "MacVariability":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.MacVariability = make(map[string]float32)
				} else {
					out.MacVariability = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v26 float32
					v26 = float32(in.Float32())
					(out.MacVariability)[key] = v26
					in.WantComma()
				}
				in.Delim('}')
			}
		case "MacCount":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.MacCount = make(map[string]int)
				} else {
					out.MacCount = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v27 int
					v27 = int(in.Int())
					(out.MacCount)[key] = v27
					in.WantComma()
				}
				in.Delim('}')
			}
		case "MacCountByLoc":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.MacCountByLoc = make(map[string]map[string]int)
				} else {
					out.MacCountByLoc = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v28 map[string]int
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						if !in.IsDelim('}') {
							v28 = make(map[string]int)
						} else {
							v28 = nil
						}
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v29 int
							v29 = int(in.Int())
							(v28)[key] = v29
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.MacCountByLoc)[key] = v28
					in.WantComma()
				}
				in.Delim('}')
			}
		case "UniqueLocs":
			if in.IsNull() {
				in.Skip()
				out.UniqueLocs = nil
			} else {
				in.Delim('[')
				if out.UniqueLocs == nil {
					if !in.IsDelim(']') {
						out.UniqueLocs = make([]string, 0, 4)
					} else {
						out.UniqueLocs = []string{}
					}
				} else {
					out.UniqueLocs = (out.UniqueLocs)[:0]
				}
				for !in.IsDelim(']') {
					var v30 string
					v30 = string(in.String())
					out.UniqueLocs = append(out.UniqueLocs, v30)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "UniqueMacs":
			if in.IsNull() {
				in.Skip()
				out.UniqueMacs = nil
			} else {
				in.Delim('[')
				if out.UniqueMacs == nil {
					if !in.IsDelim(']') {
						out.UniqueMacs = make([]string, 0, 4)
					} else {
						out.UniqueMacs = []string{}
					}
				} else {
					out.UniqueMacs = (out.UniqueMacs)[:0]
				}
				for !in.IsDelim(']') {
					var v31 string
					v31 = string(in.String())
					out.UniqueMacs = append(out.UniqueMacs, v31)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "LocCount":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.LocCount = make(map[string]int)
				} else {
					out.LocCount = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v32 int
					v32 = int(in.Int())
					(out.LocCount)[key] = v32
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b8810b5EncodeParsinServerDbm2(out *jwriter.Writer, in MiddleDataStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"NetworkMacs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.NetworkMacs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v33First := true
			for v33Name, v33Value := range in.NetworkMacs {
				if v33First {
					v33First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v33Name))
				out.RawByte(':')
				if v33Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v34First := true
					for v34Name, v34Value := range v33Value {
						if v34First {
							v34First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v34Name))
						out.RawByte(':')
						out.Bool(bool(v34Value))
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"NetworkLocs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.NetworkLocs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v35First := true
			for v35Name, v35Value := range in.NetworkLocs {
				if v35First {
					v35First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v35Name))
				out.RawByte(':')
				if v35Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v36First := true
					for v36Name, v36Value := range v35Value {
						if v36First {
							v36First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v36Name))
						out.RawByte(':')
						out.Bool(bool(v36Value))
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"MacVariability\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.MacVariability == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v37First := true
			for v37Name, v37Value := range in.MacVariability {
				if v37First {
					v37First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v37Name))
				out.RawByte(':')
				out.Float32(float32(v37Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"MacCount\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.MacCount == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v38First := true
			for v38Name, v38Value := range in.MacCount {
				if v38First {
					v38First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v38Name))
				out.RawByte(':')
				out.Int(int(v38Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"MacCountByLoc\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.MacCountByLoc == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v39First := true
			for v39Name, v39Value := range in.MacCountByLoc {
				if v39First {
					v39First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v39Name))
				out.RawByte(':')
				if v39Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v40First := true
					for v40Name, v40Value := range v39Value {
						if v40First {
							v40First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v40Name))
						out.RawByte(':')
						out.Int(int(v40Value))
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"UniqueLocs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.UniqueLocs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v41, v42 := range in.UniqueLocs {
				if v41 > 0 {
					out.RawByte(',')
				}
				out.String(string(v42))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"UniqueMacs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.UniqueMacs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v43, v44 := range in.UniqueMacs {
				if v43 > 0 {
					out.RawByte(',')
				}
				out.String(string(v44))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"LocCount\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.LocCount == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v45First := true
			for v45Name, v45Value := range in.LocCount {
				if v45First {
					v45First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v45Name))
				out.RawByte(':')
				out.Int(int(v45Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MiddleDataStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b8810b5EncodeParsinServerDbm2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MiddleDataStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b8810b5EncodeParsinServerDbm2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MiddleDataStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b8810b5DecodeParsinServerDbm2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MiddleDataStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b8810b5DecodeParsinServerDbm2(l, v)
}
func easyjson3b8810b5DecodeParsinServerDbm3(in *jlexer.Lexer, out *GroupManger) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b8810b5EncodeParsinServerDbm3(out *jwriter.Writer, in GroupManger) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GroupManger) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b8810b5EncodeParsinServerDbm3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GroupManger) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b8810b5EncodeParsinServerDbm3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GroupManger) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b8810b5DecodeParsinServerDbm3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GroupManger) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b8810b5DecodeParsinServerDbm3(l, v)
}
func easyjson3b8810b5DecodeParsinServerDbm4(in *jlexer.Lexer, out *Group) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "GMutex":
			if in.IsNull() {
				in.Skip()
				out.GMutex = nil
			} else {
				if out.GMutex == nil {
					out.GMutex = new(sync.RWMutex)
				}
				easyjson3b8810b5DecodeSync(in, &*out.GMutex)
			}
		case "Name":
			out.Name = string(in.String())
		case "Permanent":
			out.Permanent = bool(in.Bool())
		case "RawData":
			if in.IsNull() {
				in.Skip()
				out.RawData = nil
			} else {
				if out.RawData == nil {
					out.RawData = new(RawDataStruct)
				}
				(*out.RawData).UnmarshalEasyJSON(in)
			}
		case "MiddleData":
			if in.IsNull() {
				in.Skip()
				out.MiddleData = nil
			} else {
				if out.MiddleData == nil {
					out.MiddleData = new(MiddleDataStruct)
				}
				(*out.MiddleData).UnmarshalEasyJSON(in)
			}
		case "AlgoData":
			if in.IsNull() {
				in.Skip()
				out.AlgoData = nil
			} else {
				if out.AlgoData == nil {
					out.AlgoData = new(AlgoDataStruct)
				}
				(*out.AlgoData).UnmarshalEasyJSON(in)
			}
		case "ResultData":
			if in.IsNull() {
				in.Skip()
				out.ResultData = nil
			} else {
				if out.ResultData == nil {
					out.ResultData = new(ResultDataStruct)
				}
				(*out.ResultData).UnmarshalEasyJSON(in)
			}
		case "RawDataChanged":
			out.RawDataChanged = bool(in.Bool())
		case "MiddleDataChanged":
			out.MiddleDataChanged = bool(in.Bool())
		case "AlgoDataChanged":
			out.AlgoDataChanged = bool(in.Bool())
		case "ResultDataChanged":
			out.ResultDataChanged = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b8810b5EncodeParsinServerDbm4(out *jwriter.Writer, in Group) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"GMutex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.GMutex == nil {
			out.RawString("null")
		} else {
			easyjson3b8810b5EncodeSync(out, *in.GMutex)
		}
	}
	{
		const prefix string = ",\"Name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Permanent\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Permanent))
	}
	{
		const prefix string = ",\"RawData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.RawData == nil {
			out.RawString("null")
		} else {
			(*in.RawData).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"MiddleData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.MiddleData == nil {
			out.RawString("null")
		} else {
			(*in.MiddleData).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"AlgoData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.AlgoData == nil {
			out.RawString("null")
		} else {
			(*in.AlgoData).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"ResultData\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.ResultData == nil {
			out.RawString("null")
		} else {
			(*in.ResultData).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"RawDataChanged\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.RawDataChanged))
	}
	{
		const prefix string = ",\"MiddleDataChanged\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.MiddleDataChanged))
	}
	{
		const prefix string = ",\"AlgoDataChanged\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.AlgoDataChanged))
	}
	{
		const prefix string = ",\"ResultDataChanged\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.ResultDataChanged))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Group) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b8810b5EncodeParsinServerDbm4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Group) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b8810b5EncodeParsinServerDbm4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Group) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b8810b5DecodeParsinServerDbm4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Group) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b8810b5DecodeParsinServerDbm4(l, v)
}
func easyjson3b8810b5DecodeSync(in *jlexer.Lexer, out *sync.RWMutex) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b8810b5EncodeSync(out *jwriter.Writer, in sync.RWMutex) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}
func easyjson3b8810b5DecodeParsinServerDbm5(in *jlexer.Lexer, out *AlgoDataStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "KnnFPs":
			(out.KnnFPs).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b8810b5EncodeParsinServerDbm5(out *jwriter.Writer, in AlgoDataStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"KnnFPs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.KnnFPs).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AlgoDataStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b8810b5EncodeParsinServerDbm5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AlgoDataStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b8810b5EncodeParsinServerDbm5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AlgoDataStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b8810b5DecodeParsinServerDbm5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AlgoDataStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b8810b5DecodeParsinServerDbm5(l, v)
}
