// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package dbm

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func (AlgoDataStruct) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*AlgoDataStruct) UnmarshalJSON([]byte) error        { return nil }
func (AlgoDataStruct) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*AlgoDataStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AlgoDataStruct *AlgoDataStruct

func (Group) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Group) UnmarshalJSON([]byte) error        { return nil }
func (Group) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Group) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Group *Group

func (GroupManger) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GroupManger) UnmarshalJSON([]byte) error        { return nil }
func (GroupManger) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GroupManger) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GroupManger *GroupManger

func (MiddleDataStruct) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*MiddleDataStruct) UnmarshalJSON([]byte) error        { return nil }
func (MiddleDataStruct) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*MiddleDataStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MiddleDataStruct *MiddleDataStruct

func (RawDataStruct) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*RawDataStruct) UnmarshalJSON([]byte) error        { return nil }
func (RawDataStruct) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*RawDataStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RawDataStruct *RawDataStruct

func (ResultDataStruct) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ResultDataStruct) UnmarshalJSON([]byte) error        { return nil }
func (ResultDataStruct) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ResultDataStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ResultDataStruct *ResultDataStruct
