// Code generated by protoc-gen-go. DO NOT EDIT.
// source: particlefilter.proto

package particlefilterclasses

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Dot struct {
	XY                   []float32 `protobuf:"fixed32,1,rep,packed,name=XY,proto3" json:"XY,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Dot) Reset()         { *m = Dot{} }
func (m *Dot) String() string { return proto.CompactTextString(m) }
func (*Dot) ProtoMessage()    {}
func (*Dot) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{1}
}

func (m *Dot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dot.Unmarshal(m, b)
}
func (m *Dot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dot.Marshal(b, m, deterministic)
}
func (m *Dot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dot.Merge(m, src)
}
func (m *Dot) XXX_Size() int {
	return xxx_messageInfo_Dot.Size(m)
}
func (m *Dot) XXX_DiscardUnknown() {
	xxx_messageInfo_Dot.DiscardUnknown(m)
}

var xxx_messageInfo_Dot proto.InternalMessageInfo

func (m *Dot) GetXY() []float32 {
	if m != nil {
		return m.XY
	}
	return nil
}

type Line struct {
	Dots                 []*Dot   `protobuf:"bytes,1,rep,name=Dots,proto3" json:"Dots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Line) Reset()         { *m = Line{} }
func (m *Line) String() string { return proto.CompactTextString(m) }
func (*Line) ProtoMessage()    {}
func (*Line) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{2}
}

func (m *Line) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Line.Unmarshal(m, b)
}
func (m *Line) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Line.Marshal(b, m, deterministic)
}
func (m *Line) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Line.Merge(m, src)
}
func (m *Line) XXX_Size() int {
	return xxx_messageInfo_Line.Size(m)
}
func (m *Line) XXX_DiscardUnknown() {
	xxx_messageInfo_Line.DiscardUnknown(m)
}

var xxx_messageInfo_Line proto.InternalMessageInfo

func (m *Line) GetDots() []*Dot {
	if m != nil {
		return m.Dots
	}
	return nil
}

type Graph struct {
	Lines                []*Line  `protobuf:"bytes,1,rep,name=Lines,proto3" json:"Lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Graph) Reset()         { *m = Graph{} }
func (m *Graph) String() string { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()    {}
func (*Graph) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{3}
}

func (m *Graph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Graph.Unmarshal(m, b)
}
func (m *Graph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Graph.Marshal(b, m, deterministic)
}
func (m *Graph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Graph.Merge(m, src)
}
func (m *Graph) XXX_Size() int {
	return xxx_messageInfo_Graph.Size(m)
}
func (m *Graph) XXX_DiscardUnknown() {
	xxx_messageInfo_Graph.DiscardUnknown(m)
}

var xxx_messageInfo_Graph proto.InternalMessageInfo

func (m *Graph) GetLines() []*Line {
	if m != nil {
		return m.Lines
	}
	return nil
}

// Initialization:
type InitRequest struct {
	Timestamp            int64     `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XY                   []float32 `protobuf:"fixed32,2,rep,packed,name=XY,proto3" json:"XY,omitempty"`
	MapGraph             *Graph    `protobuf:"bytes,3,opt,name=MapGraph,proto3" json:"MapGraph,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{4}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *InitRequest) GetXY() []float32 {
	if m != nil {
		return m.XY
	}
	return nil
}

func (m *InitRequest) GetMapGraph() *Graph {
	if m != nil {
		return m.MapGraph
	}
	return nil
}

type InitReply struct {
	ReturnValue          bool     `protobuf:"varint,1,opt,name=ReturnValue,proto3" json:"ReturnValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitReply) Reset()         { *m = InitReply{} }
func (m *InitReply) String() string { return proto.CompactTextString(m) }
func (*InitReply) ProtoMessage()    {}
func (*InitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{5}
}

func (m *InitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReply.Unmarshal(m, b)
}
func (m *InitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReply.Marshal(b, m, deterministic)
}
func (m *InitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReply.Merge(m, src)
}
func (m *InitReply) XXX_Size() int {
	return xxx_messageInfo_InitReply.Size(m)
}
func (m *InitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReply.DiscardUnknown(m)
}

var xxx_messageInfo_InitReply proto.InternalMessageInfo

func (m *InitReply) GetReturnValue() bool {
	if m != nil {
		return m.ReturnValue
	}
	return false
}

// Predict:
type PredictRequest struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictRequest) Reset()         { *m = PredictRequest{} }
func (m *PredictRequest) String() string { return proto.CompactTextString(m) }
func (*PredictRequest) ProtoMessage()    {}
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{6}
}

func (m *PredictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictRequest.Unmarshal(m, b)
}
func (m *PredictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictRequest.Marshal(b, m, deterministic)
}
func (m *PredictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictRequest.Merge(m, src)
}
func (m *PredictRequest) XXX_Size() int {
	return xxx_messageInfo_PredictRequest.Size(m)
}
func (m *PredictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictRequest proto.InternalMessageInfo

func (m *PredictRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PredictReply struct {
	ResXY                []float32 `protobuf:"fixed32,1,rep,packed,name=ResXY,proto3" json:"ResXY,omitempty"`
	ReturnValue          bool      `protobuf:"varint,2,opt,name=ReturnValue,proto3" json:"ReturnValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PredictReply) Reset()         { *m = PredictReply{} }
func (m *PredictReply) String() string { return proto.CompactTextString(m) }
func (*PredictReply) ProtoMessage()    {}
func (*PredictReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{7}
}

func (m *PredictReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictReply.Unmarshal(m, b)
}
func (m *PredictReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictReply.Marshal(b, m, deterministic)
}
func (m *PredictReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictReply.Merge(m, src)
}
func (m *PredictReply) XXX_Size() int {
	return xxx_messageInfo_PredictReply.Size(m)
}
func (m *PredictReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictReply.DiscardUnknown(m)
}

var xxx_messageInfo_PredictReply proto.InternalMessageInfo

func (m *PredictReply) GetResXY() []float32 {
	if m != nil {
		return m.ResXY
	}
	return nil
}

func (m *PredictReply) GetReturnValue() bool {
	if m != nil {
		return m.ReturnValue
	}
	return false
}

// Update:
type UpdateRequest struct {
	Timestamp            int64     `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	MasterEstimation     []float32 `protobuf:"fixed32,2,rep,packed,name=MasterEstimation,proto3" json:"MasterEstimation,omitempty"`
	SlaveEstimation      []float32 `protobuf:"fixed32,3,rep,packed,name=SlaveEstimation,proto3" json:"SlaveEstimation,omitempty"`
	TrueLocation         []float32 `protobuf:"fixed32,4,rep,packed,name=TrueLocation,proto3" json:"TrueLocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{8}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UpdateRequest) GetMasterEstimation() []float32 {
	if m != nil {
		return m.MasterEstimation
	}
	return nil
}

func (m *UpdateRequest) GetSlaveEstimation() []float32 {
	if m != nil {
		return m.SlaveEstimation
	}
	return nil
}

func (m *UpdateRequest) GetTrueLocation() []float32 {
	if m != nil {
		return m.TrueLocation
	}
	return nil
}

type UpdateReply struct {
	ResXY                []float32 `protobuf:"fixed32,1,rep,packed,name=ResXY,proto3" json:"ResXY,omitempty"`
	ReturnValue          bool      `protobuf:"varint,2,opt,name=ReturnValue,proto3" json:"ReturnValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateReply) Reset()         { *m = UpdateReply{} }
func (m *UpdateReply) String() string { return proto.CompactTextString(m) }
func (*UpdateReply) ProtoMessage()    {}
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4594772a6ea02a, []int{9}
}

func (m *UpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReply.Unmarshal(m, b)
}
func (m *UpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReply.Marshal(b, m, deterministic)
}
func (m *UpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReply.Merge(m, src)
}
func (m *UpdateReply) XXX_Size() int {
	return xxx_messageInfo_UpdateReply.Size(m)
}
func (m *UpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReply proto.InternalMessageInfo

func (m *UpdateReply) GetResXY() []float32 {
	if m != nil {
		return m.ResXY
	}
	return nil
}

func (m *UpdateReply) GetReturnValue() bool {
	if m != nil {
		return m.ReturnValue
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "particlefilterclasses.Empty")
	proto.RegisterType((*Dot)(nil), "particlefilterclasses.Dot")
	proto.RegisterType((*Line)(nil), "particlefilterclasses.Line")
	proto.RegisterType((*Graph)(nil), "particlefilterclasses.Graph")
	proto.RegisterType((*InitRequest)(nil), "particlefilterclasses.InitRequest")
	proto.RegisterType((*InitReply)(nil), "particlefilterclasses.InitReply")
	proto.RegisterType((*PredictRequest)(nil), "particlefilterclasses.PredictRequest")
	proto.RegisterType((*PredictReply)(nil), "particlefilterclasses.PredictReply")
	proto.RegisterType((*UpdateRequest)(nil), "particlefilterclasses.UpdateRequest")
	proto.RegisterType((*UpdateReply)(nil), "particlefilterclasses.UpdateReply")
}

func init() { proto.RegisterFile("particlefilter.proto", fileDescriptor_6a4594772a6ea02a) }

var fileDescriptor_6a4594772a6ea02a = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x6f, 0x6b, 0x13, 0x41,
	0x10, 0xc6, 0xbd, 0xbb, 0xa4, 0x7f, 0xe6, 0x6a, 0x94, 0xb5, 0x85, 0x10, 0x0b, 0x1e, 0xab, 0x42,
	0x10, 0x3c, 0x30, 0x82, 0x14, 0x5f, 0xd6, 0xa4, 0x22, 0xb4, 0x10, 0xd6, 0xa8, 0xed, 0xcb, 0xf5,
	0x3a, 0xea, 0xc2, 0xde, 0xed, 0xba, 0xbb, 0x27, 0xd6, 0x2f, 0xe4, 0x67, 0xf3, 0x5b, 0xc8, 0xed,
	0x25, 0xb1, 0x97, 0x7a, 0x26, 0xe0, 0xcb, 0x9b, 0xfd, 0xcd, 0x3c, 0x73, 0xcf, 0xb3, 0x2c, 0xec,
	0x6b, 0x6e, 0x9c, 0xc8, 0x24, 0x7e, 0x12, 0xd2, 0xa1, 0x49, 0xb5, 0x51, 0x4e, 0x91, 0x83, 0x66,
	0x35, 0x93, 0xdc, 0x5a, 0xb4, 0x74, 0x1b, 0xba, 0x93, 0x5c, 0xbb, 0x2b, 0x7a, 0x00, 0xd1, 0x58,
	0x39, 0xd2, 0x83, 0xf0, 0xfc, 0xa2, 0x1f, 0x24, 0xd1, 0x30, 0x64, 0xe1, 0xf9, 0x05, 0x7d, 0x01,
	0x9d, 0x53, 0x51, 0x20, 0x49, 0xa1, 0x33, 0x56, 0xce, 0xfa, 0x93, 0x78, 0x34, 0x48, 0xff, 0x3a,
	0x2d, 0x1d, 0x2b, 0xc7, 0x3c, 0x47, 0x5f, 0x42, 0xf7, 0xb5, 0xe1, 0xfa, 0x0b, 0x79, 0x06, 0xdd,
	0x6a, 0xc0, 0xa2, 0xf3, 0x7e, 0x4b, 0x67, 0xc5, 0xb0, 0x9a, 0xa4, 0x25, 0xc4, 0x6f, 0x0a, 0xe1,
	0x18, 0x7e, 0x2d, 0xd1, 0x3a, 0x72, 0x08, 0xbb, 0x33, 0x91, 0xa3, 0x75, 0x3c, 0xd7, 0xfd, 0x20,
	0x09, 0x86, 0x11, 0xfb, 0x53, 0x98, 0x2f, 0x1c, 0x2e, 0x16, 0x26, 0x47, 0xb0, 0x73, 0xc6, 0xb5,
	0xd7, 0xee, 0x47, 0x49, 0x30, 0x8c, 0x47, 0x87, 0x2d, 0x92, 0x9e, 0x61, 0x4b, 0x9a, 0x3e, 0x85,
	0xdd, 0x5a, 0x56, 0xcb, 0x2b, 0x92, 0x40, 0xcc, 0xd0, 0x95, 0xa6, 0x78, 0xcf, 0x65, 0x89, 0x5e,
	0x76, 0x87, 0x5d, 0x2f, 0xd1, 0x14, 0x7a, 0x53, 0x83, 0x97, 0x22, 0xdb, 0x6c, 0x51, 0x7a, 0x02,
	0x7b, 0x4b, 0xbe, 0x52, 0xd8, 0x87, 0x2e, 0x43, 0xbb, 0x34, 0xbb, 0xfe, 0x58, 0xd5, 0x0d, 0x6f,
	0xea, 0xfe, 0x0c, 0xe0, 0xf6, 0x3b, 0x7d, 0xc9, 0x1d, 0x6e, 0x66, 0xd0, 0x13, 0xb8, 0x7b, 0xc6,
	0xad, 0x43, 0x33, 0xb1, 0x4e, 0xe4, 0xdc, 0x09, 0x55, 0xcc, 0xed, 0xba, 0x51, 0x27, 0x43, 0xb8,
	0xf3, 0x56, 0xf2, 0x6f, 0x78, 0x0d, 0x8d, 0x3c, 0xba, 0x5a, 0x26, 0x14, 0xf6, 0x66, 0xa6, 0xc4,
	0x53, 0x95, 0xd5, 0x58, 0xc7, 0x63, 0x8d, 0x1a, 0x9d, 0x40, 0xbc, 0x58, 0xf4, 0x3f, 0x7e, 0x78,
	0xf4, 0x2b, 0x84, 0xde, 0x74, 0x9e, 0xe0, 0x89, 0x4f, 0x90, 0x30, 0xe8, 0xbd, 0x52, 0x45, 0x81,
	0x59, 0xa5, 0x33, 0xf3, 0x1e, 0xb4, 0x84, 0xec, 0x2f, 0xf7, 0x20, 0x69, 0x39, 0x5d, 0xe6, 0x4d,
	0x6f, 0x91, 0x19, 0x40, 0xf5, 0x29, 0xb8, 0x14, 0x3f, 0x90, 0xd0, 0x7f, 0x76, 0x78, 0xdf, 0x37,
	0x9a, 0xfa, 0x01, 0xb6, 0xe7, 0xa9, 0x93, 0xc7, 0x2d, 0x78, 0xf3, 0x16, 0x0d, 0x1e, 0xae, 0xc3,
	0x16, 0xeb, 0x6e, 0xd5, 0xe6, 0x92, 0x47, 0x2d, 0x0d, 0x8d, 0x4b, 0x32, 0xa0, 0x6b, 0x28, 0x3f,
	0xf5, 0xf8, 0x08, 0x1e, 0x08, 0x95, 0x7e, 0x36, 0x3a, 0x4b, 0xf1, 0x3b, 0xcf, 0xb5, 0x44, 0xbb,
	0xd2, 0x77, 0x7c, 0xaf, 0x99, 0xc5, 0xb4, 0x7a, 0x5d, 0xa6, 0xc1, 0xc7, 0x2d, 0xff, 0xcc, 0x3c,
	0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xcd, 0x37, 0xdb, 0x7e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ParticleFilterClient is the client API for ParticleFilter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParticleFilterClient interface {
	// Initialization
	ConnectionTest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InitReply, error)
	// Initialization
	Initialize(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitReply, error)
	// Predict
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error)
	// Update
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateReply, error)
}

type particleFilterClient struct {
	cc *grpc.ClientConn
}

func NewParticleFilterClient(cc *grpc.ClientConn) ParticleFilterClient {
	return &particleFilterClient{cc}
}

func (c *particleFilterClient) ConnectionTest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InitReply, error) {
	out := new(InitReply)
	err := c.cc.Invoke(ctx, "/particlefilterclasses.ParticleFilter/ConnectionTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *particleFilterClient) Initialize(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitReply, error) {
	out := new(InitReply)
	err := c.cc.Invoke(ctx, "/particlefilterclasses.ParticleFilter/Initialize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *particleFilterClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error) {
	out := new(PredictReply)
	err := c.cc.Invoke(ctx, "/particlefilterclasses.ParticleFilter/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *particleFilterClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateReply, error) {
	out := new(UpdateReply)
	err := c.cc.Invoke(ctx, "/particlefilterclasses.ParticleFilter/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParticleFilterServer is the server API for ParticleFilter service.
type ParticleFilterServer interface {
	// Initialization
	ConnectionTest(context.Context, *Empty) (*InitReply, error)
	// Initialization
	Initialize(context.Context, *InitRequest) (*InitReply, error)
	// Predict
	Predict(context.Context, *PredictRequest) (*PredictReply, error)
	// Update
	Update(context.Context, *UpdateRequest) (*UpdateReply, error)
}

func RegisterParticleFilterServer(s *grpc.Server, srv ParticleFilterServer) {
	s.RegisterService(&_ParticleFilter_serviceDesc, srv)
}

func _ParticleFilter_ConnectionTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticleFilterServer).ConnectionTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/particlefilterclasses.ParticleFilter/ConnectionTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticleFilterServer).ConnectionTest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParticleFilter_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticleFilterServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/particlefilterclasses.ParticleFilter/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticleFilterServer).Initialize(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParticleFilter_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticleFilterServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/particlefilterclasses.ParticleFilter/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticleFilterServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParticleFilter_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticleFilterServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/particlefilterclasses.ParticleFilter/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticleFilterServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ParticleFilter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "particlefilterclasses.ParticleFilter",
	HandlerType: (*ParticleFilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectionTest",
			Handler:    _ParticleFilter_ConnectionTest_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _ParticleFilter_Initialize_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _ParticleFilter_Predict_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ParticleFilter_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "particlefilter.proto",
}
